{% set version = "3.3.7" %}
{% set buildnumber = 0 %}

package:
  name: fftw-parallel
  version: {{ version }}

source:
  fn: fftw-{{ version }}.tar.gz
  url: http://www.fftw.org/fftw-{{ version }}.tar.gz
  sha256: 3b609b7feba5230e8f6dd8d245ddbefac324c5a6ae4186947670d9ac2cd25573

build:
  number: {{buildnumber}}

requirements:
  build:
    - perl 5.22.2.1  # [not win]

about:
  home: http://fftw.org
  license: GPL 2
  summary: "The fastest Fourier transform in the west."
